In [2]:
import csv

with open('datos_generales.txt', 'r') as txtfile:
    txtreader = csv.reader(txtfile, delimiter='|')

    with open('datos_ofuscados.csv', 'w', newline='') as csvfile:
        csvwriter = csv.writer(csvfile)

        for row in txtreader:
            csvwriter.writerow(row)

In [3]:
import pandas as pd

file_path = 'datos_ofuscados.csv'
df = pd.read_csv(file_path)

df.head()

,FEC_CONS,FEC_PROC,TIP_TRAN,IMP_ORI_TOT,MON_IMP,IMP_DES,PAR_DES,CVE_COM,MCC,NOM_COM,plasticoF,ClienteF,tipo
0,28FEB2021:00:00:00.000000,01MAR2021,1,409.57,484,409.57,0.0000,1008440,5411,SORIANA343 GARZA SADA,F9B9D796848AF6B19CE60682F5632F0CF500CADF7190B6...,0007ADBB921C28F452E4A6AC20C1B42A0FC94613163048...,TDD
1,01MAR2021:00:00:00.000000,02MAR2021,1,17.00,484,17.00,20.6123,10025426,5815,APPLE.COM/BILL,F9B9D796848AF6B19CE60682F5632F0CF500CADF7190B6...,0007ADBB921C28F452E4A6AC20C1B42A0FC94613163048...,TDD
2,02MAR2021:00:00:00.000000,04MAR2021,1,69.00,484,69.00,0.0000,6041503,5499,7 ELEVEN HILARIO MTZ,F9B9D796848AF6B19CE60682F5632F0CF500CADF7190B6...,0007ADBB921C28F452E4A6AC20C1B42A0FC94613163048...,TDD
3,02MAR2021:20:15:02.000000,02MAR2021,1,998.37,484,998.37,0.0000,7895432,5411,MERCO NUEVO REPUBLO,F9B9D796848AF6B19CE60682F5632F0CF500CADF7190B6...,0007ADBB921C28F452E4A6AC20C1B42A0FC94613163048...,TDD
4,03MAR2021:00:00:00.000000,04MAR2021,1,259.00,484,259.00,0.0000,7948490,5499,7 ELEVEN PALESTINA,F9B9D796848AF6B19CE60682F5632F0CF500CADF7190B6...,0007ADBB921C28F452E4A6AC20C1B42A0FC94613163048...,TDD

In [7]:
from nltk.stem import PorterStemmer
import string
import re

def preprocess_text_advanced(text):
    text = text.lower()
    text = re.sub(r'\d+', '', text)
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = text.strip()
    return text

df.to_csv('datos_ofuscados_preprocessed.csv', index=False)
df['NOM_COM_clean_advanced'] = df['NOM_COM'].apply(preprocess_text_advanced)

In [8]:
keywords_dict = {
    'Food': ['restaurant', 'meat', 'mochis', 'baguet', 'maria bonita', 'italia', 'nipon', 'fries', 'dazs', 'asturi', 'ramos', 'timon', 'fish', 'applebees', 'yog', 'pizz', 'vino', 'bowl', 'lobster', 'pozole', 'bake', 'pay', 'modelor', 'mirai', 'maris', 'palmit', 'siber', 'rocket', 'bbq', 'hooter', 'cow', 'gourmet', 'elote', 'salad', 'pesca', 'cof', 'dq', 'camaron', 'denny', 'beer', 'tabern', 'vegan', 'veget', 'grill', 'lunch', 'brunch', 'maiz', 'nestle', 'la mexicana', 'granos', 'froyo', 'churr', 'cinnab', 'cerve', 'chicken', 'chocola', 'almuerzo', 'cantina', 'bimbo', 'birri', 'bar', 'tak', 'aliment', 'gelato', 'cocina', 'food', 'nutrisa', 'sushi', 'maison', 'pf', 'parril', 'chil', 'botan', 'starbuck', 'sanborn', 'pan', 'bis', 'toks', 'crep', 'asad', 'cremer', 'tostada', 'comi', 'buffet', 'cabrito', 'lacteo', 'cafe', 'pastor', 'pizza',  'mcdonalds', 'buffalo',  '7 eleven',  '7eleven','busha', 'bucha', 'monch', 'pollo', 'sayu', 'muncher', 'oxxo', 'rappi', 'rest',  'carls', 'little', 'subway', 'kfc', 'coffee', 'tortas', 'church', 'dominos', 'sazon', 'sirloin', 'josephinos', 'pastel', 'mc', 'taco', 'dairy', 'taque', 'jac', 'patsel', 'bur',  'wing', 'alita', 'antoj', 'vips', 'spikes', 'dona', 'repost', 'helado', 'el chino', 'sirlon', 'frut', 'bueneros', 'dulce', 'nacho', 'cafe', 'caffe'],
    'Transport': ['uber', 'senda', 'transp', 'est', 'mobility', 'ado', 'taxi', 'bus', 'metro', 'didi rides', 'cabify', 'lyft', 'taxify', 'didimx'],
    'Clothes': ['ropa', 'shoe', 'flexi', 'secret', 'vertiche', 'puma', 'taf', 'tj', 'moda', 'ross', 'fashion', 'old navy', 'marshall', 'vuitton', 'jcpen', 'jean', 'hugo boss', 'gucci', 'gaynor', 'outlet', 'closet', 'c a', 'bols', 'plat', 'aldo conti', 'h&m', 'h & m', 'zara', 'p&b', 'bsk',  'shein', 'joy', 'swatch', 'textil', 'soho', 'lefties', 'zap', 'adidas', 'suburbia', 'nike', 'tienda', 'mall', 'pull', 'shasa', 'telas', 'bersh', 'american eagle'],
    'Health': ['far', 'arceo', 'med', 'lux', 'hos', 'fam', 'dent', 'podol', 'doct', 'dr', 'consult',  'salud', 'odont', 'quiro', 'chopo',  'gnc', 'drog', 'opti', 'hospital', 'clinica', 'benavi', 'ahorro', 'lab', 'derma'],
    'Entertainment': ['cine', 'foto', 'mubi', 'xbox', 'paramount', 'nintend', 'tinder', 'activision', 'youtube', 'roblox', 'game', 'gandhi', 'unicornio', 'ticket', 'riot', 'cultura', 'hbo', 'sorteo', 'crunchyroll', 'vix', 'noctur', 'dragon', 'boler', 'bolet', 'arena', 'auditorio', 'juguet', 'porrua', 'book', 'teatro', 'arte', 'vide', 'play', 'garena', 'musica', 'mixup', 'juegos', 'spotify', 'prime', 'netflix', 'disney', 'izzi', 'totalplay',  'megacable', 'cel'],
    'Technology': ['apple', 'mac',  'iphone', 'computadora', 'software', 'hardware', 'dell', 'samsung', 'microsoft', 'electronics', 'tvc', 'pc', ],
    'Services': ['cfe', 'deez', 'times', 'godadd', 'ser', 'movist', 'inversio', 'gayosso', 'estafeta', 'envia', 'dhl', 'go dadd', 'canva', 'cable', 'at&t',  'att','seguro', 'univers', 'midjourney', 'adobe', 'tintor', 'zoom', 'storage', 'ayunt', 'agua', 'tel', 'petro', 'gas', 'finanz', 'naturgy', 'gob', 'munici'],
    'Viajes': ['airbnb', 'magni', 'gran plaza', 'turis', 'inn', 'teso', 'expedia', 'hotel', 'aerom', 'aeropuer', 'premier'],
    'Casa': ['home', 'imper', 'invern', 'cmx', 'comex', 'plom', 'casa', 'clima', 'ferr', 'refri', 'elect', 'tornill', 'infonavit'],
    'Vehiculo': ['auto', 'refac', 'toyota', 'nissan', 'hyund', 'vehi', 'conces', 'wash', 'car', 'moto', 'llant', 'ford', 'audi', ],
    'Departamental': ['ekt', 'sol', 'coppel', 'boutique', 'body', 'liver', 'palacio', 'sears', 'bazar'],
    'Super': ['cost', 'mark', 'circle k', 'mart', 'cityclub', 'retail', 'ctral', 'central', 'abast', 'abrr', 'abts', 'comer', 'merca', 'sam', 'almacen', 'mayore', 'chedra', 'city', 'aur', 'sup', 'jokr', 'city club', 'soriana', 'merco', 'grocery', 'abar', 'wal', 'heb', 'bodeg', 'h-e', 'target'],
    'Mascotas': ['vet', 'pet', 'acua', 'animal'],
    'Deportes': ['padel', 'dep', 'fitness', 'chivas', 'sultanes', 'deca', 'gym', 'mlb'],
    'Educacion': ['uni', 'uvm', 'ccu'],
    'Belleza': ['nail'],
    'Compras en Linea': ['amazon', 'google', 'shopee', 'shoppe', 'ebay', 'paypal, aliex', 'wish', 'shopify', 'aliexpress'],
    'Otros':["plasticos", 'mateco', 'miniso', 'office', 'tela', 'clip', 'manualidades', 'papel', 'cuero', 'paris', 'nuevo mund', 'regal', 'fantas'],
    
    # Agregar en Otros Plasticos y Telas y Nombre 
    # Amazon y Shopee entrar en Compras en Linea
    # Modelos Watson x Categorizarloszz
}

def label_category(name):
    name_lower = name.lower()
    for category, keywords in keywords_dict.items():
        if any(keyword in name_lower for keyword in keywords):
            return category
    return 'Miscellaneous'

df['Category'] = df['NOM_COM'].apply(label_category)
df.to_csv('datos_ofuscados_reprocessed.csv', index=False)
df[['NOM_COM', 'Category']].head()
misc_df = df[df['Category'] == 'Miscellaneous'][['NOM_COM', 'Category']]
print(misc_df)

                      NOM_COM       Category
78              TH MICROPOLIS  Miscellaneous
81              BAE RIO NAZAS  Miscellaneous
89              BAE RIO NAZAS  Miscellaneous
135            IZ  COMPRABIEN  Miscellaneous
153            S S SAN CONTRY  Miscellaneous
...                       ...            ...
26166     LIB GONVILL GRA PZA  Miscellaneous
26169  ZTL*DISTRIBUIDORAARCAC  Miscellaneous
26190       UXIXC GUADALAJARA  Miscellaneous
26200            QIN GALERIAS  Miscellaneous
26201            QIN GALERIAS  Miscellaneous

[2718 rows x 2 columns]

In [9]:
from sklearn.decomposition import TruncatedSVD
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X_tfidf = vectorizer.fit_transform(df['NOM_COM_clean_advanced'])
svd = TruncatedSVD(n_components=100)
X_reduced = svd.fit_transform(X_tfidf)

reduced_df = pd.DataFrame(X_reduced)
reduced_df.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,4.751675e-08,2.837340e-06,1.381499e-06,2.923173e-05,3.283299e-05,1.444106e-04,-9.396131e-08,-6.407855e-08,3.022909e-04,1.399090e-03,...,1.307660e-02,4.538801e-02,2.468631e-02,-4.462623e-02,9.533245e-02,-1.499750e-01,2.219731e-02,8.334939e-02,-1.006324e-01,-1.558427e-02
1,-1.106547e-15,1.176811e-12,2.353115e-12,9.880914e-12,-8.947002e-12,4.454615e-10,1.000000e+00,4.062895e-11,-5.224529e-11,6.018687e-11,...,4.300547e-08,-1.507514e-08,-1.655541e-08,-3.710754e-09,-2.581719e-08,-1.609767e-08,8.045197e-12,-2.234423e-08,-4.428914e-08,-1.882021e-10
2,6.483954e-09,4.784116e-06,3.480608e-07,1.492552e-04,3.086425e-04,6.568670e-01,2.343699e-09,-1.281703e-06,-4.298432e-04,-3.037109e-04,...,6.053724e-03,1.324218e-02,8.148949e-03,4.450901e-03,-1.454408e-03,1.178906e-03,3.955885e-03,2.168298e-03,3.605341e-04,5.444168e-03
3,4.354195e-10,8.078278e-08,4.187903e-08,3.393272e-06,2.289762e-05,3.647615e-05,-6.956984e-08,-1.089194e-07,1.369117e-04,4.666830e-05,...,-7.464716e-02,3.116393e-02,-4.313059e-02,7.023339e-02,-3.712460e-02,-1.249538e-02,5.801421e-02,9.164897e-02,2.753775e-02,4.350021e-03
4,1.600063e-08,4.810424e-06,5.616792e-07,1.125402e-04,2.518191e-04,4.901116e-01,7.693660e-09,-9.763682e-07,-3.557661e-04,9.059737e-05,...,-9.588239e-03,-2.700417e-02,-1.121790e-02,5.505986e-03,1.913899e-03,-7.041409e-03,-6.616701e-03,-1.781727e-03,-1.866221e-03,-1.865364e-03

In [10]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score

scaler = MinMaxScaler()

X_scaled = scaler.fit_transform(X_reduced)

y = df['Category']
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier(n_estimators=100, random_state=42)
rf_clf.fit(X_train, y_train)

rf_y_pred = rf_clf.predict(X_test)
rf_accuracy = accuracy_score(y_test, rf_y_pred)
rf_f1 = f1_score(y_test, rf_y_pred, average='weighted')

rf_accuracy, rf_f1

#Obtener el % de miscelaneos

(0.9418826219512195, 0.942329782256323)

In [11]:
test_df = pd.read_csv("datos_test.csv")

test_df['NOM_COM_clean_advanced'] = test_df['NOM_COM'].apply(preprocess_text_advanced)
X_test_tfidf = vectorizer.transform(test_df['NOM_COM_clean_advanced'])
X_test_reduced = svd.transform(X_test_tfidf)
X_test_scaled = scaler.transform(X_test_reduced)

test_df['Predicted_Category'] = rf_clf.predict(X_test_scaled)

test_dataset_with_predictions_path = 'test_dataset_with_predictions.csv'
test_df.to_csv(test_dataset_with_predictions_path, index=False)
test_dataset_with_predictions_path

'test_dataset_with_predictions.csv'