In [1]:
import csv

with open('datos_generales.txt', 'r') as txtfile:
    txtreader = csv.reader(txtfile, delimiter='|')

    with open('datos_ofuscados.csv', 'w', newline='') as csvfile:
        csvwriter = csv.writer(csvfile)

        for row in txtreader:
            csvwriter.writerow(row)

In [2]:
import pandas as pd

file_path = 'datos_ofuscados.csv'
df = pd.read_csv(file_path)

df.head()

,FEC_CONS,FEC_PROC,TIP_TRAN,IMP_ORI_TOT,MON_IMP,IMP_DES,PAR_DES,CVE_COM,MCC,NOM_COM,plasticoF,ClienteF,tipo
0,28FEB2021:00:00:00.000000,01MAR2021,1,409.57,484,409.57,0.0000,1008440,5411,SORIANA343 GARZA SADA,F9B9D796848AF6B19CE60682F5632F0CF500CADF7190B6...,0007ADBB921C28F452E4A6AC20C1B42A0FC94613163048...,TDD
1,01MAR2021:00:00:00.000000,02MAR2021,1,17.00,484,17.00,20.6123,10025426,5815,APPLE.COM/BILL,F9B9D796848AF6B19CE60682F5632F0CF500CADF7190B6...,0007ADBB921C28F452E4A6AC20C1B42A0FC94613163048...,TDD
2,02MAR2021:00:00:00.000000,04MAR2021,1,69.00,484,69.00,0.0000,6041503,5499,7 ELEVEN HILARIO MTZ,F9B9D796848AF6B19CE60682F5632F0CF500CADF7190B6...,0007ADBB921C28F452E4A6AC20C1B42A0FC94613163048...,TDD
3,02MAR2021:20:15:02.000000,02MAR2021,1,998.37,484,998.37,0.0000,7895432,5411,MERCO NUEVO REPUBLO,F9B9D796848AF6B19CE60682F5632F0CF500CADF7190B6...,0007ADBB921C28F452E4A6AC20C1B42A0FC94613163048...,TDD
4,03MAR2021:00:00:00.000000,04MAR2021,1,259.00,484,259.00,0.0000,7948490,5499,7 ELEVEN PALESTINA,F9B9D796848AF6B19CE60682F5632F0CF500CADF7190B6...,0007ADBB921C28F452E4A6AC20C1B42A0FC94613163048...,TDD

In [3]:
def get_category(num):
    categories_ranges = {
        "Agricultura": (0, 1499),
        "Servicios_Contratados": (1500, 2999),
        "Transporte": (4000, 4799),
        "Servicios_Utilidad": (4800, 4999),
        "Retail": (5000, 5599),
        "Ropa": (5600, 5699),
        "Miscellaneous": (5700, 7299),
        "Servicios_Negocios": (7300, 7999),
        "Membresias": (8000, 8999),
        "Gobierno": (9000, 9999)
    }
    for category, (start, end) in categories_ranges.items():
        if start <= num <= end:
            return category
    return 'Miscellaneous'

In [4]:
df['Category'] = df['MCC'].apply(get_category)
df.to_csv('datos_ofuscados_reprocessed.csv', index=False)
df[['MCC', 'Category']].head()
misc_df = df[df['Category'] == 'Miscellaneous'][['MCC', 'Category']]
print(misc_df)

        MCC       Category
1      5815  Miscellaneous
8      5814  Miscellaneous
12     5814  Miscellaneous
14     5814  Miscellaneous
33     5812  Miscellaneous
...     ...            ...
26207  5814  Miscellaneous
26217  5814  Miscellaneous
26219  5912  Miscellaneous
26220  5912  Miscellaneous
26221  5818  Miscellaneous

[5027 rows x 2 columns]